/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opac;

import java.awt.Color;
import javax.swing.Box;
import javax.swing.JOptionPane;
/**
 *
 * @author MudPoet
 */
public class loginn extends javax.swing.JFrame {

    /**
     * Creates new form loginn
     */
    connection cn = new connection();
    public loginn() {
        initComponents();
        
        lblcopy.setText("Copyright \u00a9 St. Cecilia's College, Inc. All Rights Reserved. ");
        
        jMenu1.setText("Account");
        jMenuBar1.add(Box.createHorizontalGlue());
        jMenuBar1.add(jMenu1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblopac = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtusrnm = new javax.swing.JTextField();
        txtpsswrd = new javax.swing.JPasswordField();
        lblfp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblcopy = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmsearch = new javax.swing.JMenu();
        jmfind = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmabout = new javax.swing.JMenu();
        jmservices = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmmisvis = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmrules = new javax.swing.JMenuItem();
        jmabout1 = new javax.swing.JMenu();
        jmservices1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmmisvis1 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmrules1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(450, 0));
        setMinimumSize(new java.awt.Dimension(700, 621));
        setResizable(false);
        getContentPane().setLayout(null);

        lblopac.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        lblopac.setForeground(new java.awt.Color(255, 255, 255));
        lblopac.setText("Online Public Access Catalog");
        lblopac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblopacMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblopacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblopacMouseExited(evt);
            }
        });
        getContentPane().add(lblopac);
        lblopac.setBounds(20, 10, 370, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 40, 100, 30);

        jLabel6.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 80, 100, 30);

        txtusrnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusrnmActionPerformed(evt);
            }
        });
        jPanel1.add(txtusrnm);
        txtusrnm.setBounds(160, 40, 250, 30);
        jPanel1.add(txtpsswrd);
        txtpsswrd.setBounds(160, 80, 250, 30);

        lblfp.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lblfp.setForeground(new java.awt.Color(51, 51, 51));
        lblfp.setText("Forgot Password?");
        lblfp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblfpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblfpMouseExited(evt);
            }
        });
        jPanel1.add(lblfp);
        lblfp.setBounds(160, 120, 130, 30);

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 150, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 310, 460, 200);

        lblcopy.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblcopy.setText("Copyright u00a9 St. Cecilia's College, Inc. All Rights reserved. ");
        lblcopy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcopyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcopyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcopyMouseExited(evt);
            }
        });
        getContentPane().add(lblcopy);
        lblcopy.setBounds(200, 530, 360, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opac/mn66.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 700, 600);

        jmsearch.setForeground(new java.awt.Color(255, 0, 51));
        jmsearch.setText("Search");
        jmsearch.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsearchActionPerformed(evt);
            }
        });

        jmfind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmfind.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmfind.setForeground(new java.awt.Color(255, 0, 51));
        jmfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opac/srch.png"))); // NOI18N
        jmfind.setText("Find");
        jmfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmfindActionPerformed(evt);
            }
        });
        jmsearch.add(jmfind);

        jMenuBar1.add(jmsearch);

        jMenu1.setForeground(new java.awt.Color(255, 0, 51));
        jMenu1.setText("Account");
        jMenu1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem2.setText("Register");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jmabout.setForeground(new java.awt.Color(255, 0, 51));
        jmabout.setText("About");
        jmabout.setContentAreaFilled(false);
        jmabout.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmabout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jmabout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jmservices.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmservices.setForeground(new java.awt.Color(255, 0, 51));
        jmservices.setText("Services");
        jmservices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmservicesActionPerformed(evt);
            }
        });
        jmabout.add(jmservices);
        jmabout.add(jSeparator1);

        jmmisvis.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmmisvis.setForeground(new java.awt.Color(255, 0, 51));
        jmmisvis.setText("Mission/Vision");
        jmmisvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmmisvisActionPerformed(evt);
            }
        });
        jmabout.add(jmmisvis);
        jmabout.add(jSeparator2);

        jmrules.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmrules.setForeground(new java.awt.Color(255, 0, 51));
        jmrules.setText("Rules and Regulation");
        jmrules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmrulesActionPerformed(evt);
            }
        });
        jmabout.add(jmrules);

        jMenu1.add(jmabout);

        jMenuBar1.add(jMenu1);

        jmabout1.setForeground(new java.awt.Color(255, 0, 51));
        jmabout1.setText("About");
        jmabout1.setContentAreaFilled(false);
        jmabout1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmabout1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jmabout1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jmservices1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmservices1.setForeground(new java.awt.Color(255, 0, 51));
        jmservices1.setText("Services");
        jmservices1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmservices1ActionPerformed(evt);
            }
        });
        jmabout1.add(jmservices1);
        jmabout1.add(jSeparator3);

        jmmisvis1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmmisvis1.setForeground(new java.awt.Color(255, 0, 51));
        jmmisvis1.setText("Mission/Vision");
        jmmisvis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmmisvis1ActionPerformed(evt);
            }
        });
        jmabout1.add(jmmisvis1);
        jmabout1.add(jSeparator4);

        jmrules1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmrules1.setForeground(new java.awt.Color(255, 0, 51));
        jmrules1.setText("Rules and Regulation");
        jmrules1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmrules1ActionPerformed(evt);
            }
        });
        jmabout1.add(jmrules1);

        jMenuBar1.add(jmabout1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblopacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopacMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Main().setVisible(true);

    }//GEN-LAST:event_lblopacMouseClicked

    private void lblopacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopacMouseEntered
        // TODO add your handling code here:
        this.lblopac.setForeground(Color.BLACK);
        this.lblopac.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblopacMouseEntered

    private void lblopacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopacMouseExited
        // TODO add your handling code here:
        this.lblopac.setForeground(Color.WHITE);
        this.lblopac.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblopacMouseExited

    private void txtusrnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusrnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusrnmActionPerformed

    private void lblfpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfpMouseEntered
        // TODO add your handling code here:
        this.lblfp.setForeground(Color.RED);
        this.lblfp.setForeground(Color.RED);
    }//GEN-LAST:event_lblfpMouseEntered

    private void lblfpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfpMouseExited
        // TODO add your handling code here:
        this.lblfp.setForeground(Color.BLACK);
        this.lblfp.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblfpMouseExited

    private void lblfpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfpMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Please ask the Head Librarian for your password!!");
    }//GEN-LAST:event_lblfpMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String user = txtusrnm.getText(); 
       String pass = txtpsswrd.getText(); 
        try
		{
			cn.rs = cn.stmt.executeQuery("SELECT * from register WHERE adminUSERNAME = '" + user + "' and adminPASSWORD = '" + pass + "' ");
			
			if(cn.rs.next())
			{
                            
				// Displaying in text are
				JOptionPane.showMessageDialog(null,"Login Successful..!!");
				//txtpass.setText(cn.rs.getString("username") + "" + cn.rs.getString("password"));
                                this.setVisible(false);
                                String id=txtusrnm.getText();
                                Books form=new Books(id);
                                form.setVisible(true);
                                txtusrnm.setText(null);
                                txtpsswrd.setText(null);
                                
                                
                                
                                
			}
                        else

                        {
                            JOptionPane.showMessageDialog(null,"Login Failed.....!!!");
                            txtusrnm.setText(null);
                            txtpsswrd.setText(null);
                        }
		}
		catch(Exception e)
		{
			JOptionPane.showMessageDialog(null,"Error..!!");
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblcopyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcopyMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblcopyMouseClicked

    private void lblcopyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcopyMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_lblcopyMouseEntered

    private void lblcopyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcopyMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_lblcopyMouseExited

    private void jmfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmfindActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Zearch().setVisible(true);
    }//GEN-LAST:event_jmfindActionPerformed

    private void jmsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jmsearchActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new reg().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmservicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmservicesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new serve().setVisible(true);

    }//GEN-LAST:event_jmservicesActionPerformed

    private void jmmisvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmmisvisActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new vismis().setVisible(true);

    }//GEN-LAST:event_jmmisvisActionPerformed

    private void jmrulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmrulesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new rul().setVisible(true);

    }//GEN-LAST:event_jmrulesActionPerformed

    private void jmservices1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmservices1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new serve().setVisible(true);

    }//GEN-LAST:event_jmservices1ActionPerformed

    private void jmmisvis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmmisvis1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new vismis().setVisible(true);

    }//GEN-LAST:event_jmmisvis1ActionPerformed

    private void jmrules1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmrules1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new rul().setVisible(true);

    }//GEN-LAST:event_jmrules1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu jmabout;
    private javax.swing.JMenu jmabout1;
    private javax.swing.JMenuItem jmfind;
    private javax.swing.JMenuItem jmmisvis;
    private javax.swing.JMenuItem jmmisvis1;
    private javax.swing.JMenuItem jmrules;
    private javax.swing.JMenuItem jmrules1;
    private javax.swing.JMenu jmsearch;
    private javax.swing.JMenuItem jmservices;
    private javax.swing.JMenuItem jmservices1;
    private javax.swing.JLabel lblcopy;
    private javax.swing.JLabel lblfp;
    private javax.swing.JLabel lblopac;
    private javax.swing.JPasswordField txtpsswrd;
    private javax.swing.JTextField txtusrnm;
    // End of variables declaration//GEN-END:variables
}
