/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opac;

import java.awt.Color;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author MudPoet
 */
public class reg extends javax.swing.JFrame {

   
    
    connection cn = new connection();
    connection cnn = new connection();
    public reg() {
        initComponents();
        
        
        cbxcourse.setSelectedIndex(-1);
        ta.setLineWrap(true);
        ta.setWrapStyleWord(true);
        jMenu1.setText("Account");
        jMenuBar1.add(Box.createHorizontalGlue());
        jMenuBar1.add(jMenu1);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblopac2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtfull = new javax.swing.JTextField();
        cbxcourse = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        chckbxtac = new javax.swing.JCheckBox();
        txtpass = new javax.swing.JPasswordField();
        txtconpass = new javax.swing.JPasswordField();
        txtauth = new javax.swing.JPasswordField();
        btnreg = new javax.swing.JButton();
        btnsearch1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmsearch = new javax.swing.JMenu();
        jmfind = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmabout = new javax.swing.JMenu();
        jmservices = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmmisvis = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmrules = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 0));
        setMaximumSize(new java.awt.Dimension(700, 721));
        setMinimumSize(new java.awt.Dimension(700, 721));
        setPreferredSize(new java.awt.Dimension(700, 721));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        lblopac2.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        lblopac2.setForeground(new java.awt.Color(255, 255, 255));
        lblopac2.setText("Online Public Access Catalog");
        lblopac2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblopac2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblopac2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblopac2MouseExited(evt);
            }
        });
        getContentPane().add(lblopac2);
        lblopac2.setBounds(340, 10, 340, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        jPanel1.setMaximumSize(null);
        jPanel1.setLayout(null);
        jPanel1.add(txtfull);
        txtfull.setBounds(240, 20, 350, 30);

        cbxcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BS in Information Technology (BSIT)", "BS in Hospitality Management/HRM (BSHM)", "BS in Tourism Management (BSTM)", "BS in Elementary Education (BEED)", "BS in Business Administration (BSBA)", "Associate In Computer Technology (ACT)" }));
        jPanel1.add(cbxcourse);
        cbxcourse.setBounds(240, 60, 350, 30);

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Full Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 120, 30);

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Course:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 60, 120, 30);

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Authentication Code:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 200, 30);

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 140, 100, 30);
        jPanel1.add(txtuser);
        txtuser.setBounds(240, 140, 350, 30);

        jLabel6.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 180, 100, 30);

        ta.setEditable(false);
        ta.setColumns(20);
        ta.setForeground(new java.awt.Color(51, 51, 51));
        ta.setLineWrap(true);
        ta.setRows(5);
        ta.setText("Welcome to St. Cecilia's College - Cebu Library. Upon registering you should be an admin and has the authorization to modify/change the content and information of this website.\n\nPlease be responsible enough of your task and be reminded to remember the authorization code for it will be used in your future action.\n\nThank You!!!");
        jScrollPane1.setViewportView(ta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 260, 590, 130);

        jLabel9.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Confirm Password:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 220, 190, 30);

        chckbxtac.setBackground(new java.awt.Color(255, 255, 255));
        chckbxtac.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        chckbxtac.setForeground(new java.awt.Color(204, 0, 0));
        chckbxtac.setText("Terms and Condition");
        jPanel1.add(chckbxtac);
        chckbxtac.setBounds(380, 400, 230, 23);
        jPanel1.add(txtpass);
        txtpass.setBounds(240, 180, 350, 30);
        jPanel1.add(txtconpass);
        txtconpass.setBounds(240, 220, 350, 30);
        jPanel1.add(txtauth);
        txtauth.setBounds(240, 100, 350, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 160, 630, 440);

        btnreg.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnreg.setForeground(new java.awt.Color(204, 0, 0));
        btnreg.setText("Register");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });
        getContentPane().add(btnreg);
        btnreg.setBounds(410, 610, 120, 40);

        btnsearch1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnsearch1.setForeground(new java.awt.Color(204, 0, 0));
        btnsearch1.setText("Cancel");
        btnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch1);
        btnsearch1.setBounds(540, 610, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opac/mn5.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(700, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(700, 800));
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 800));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        jmsearch.setForeground(new java.awt.Color(255, 0, 51));
        jmsearch.setText("Search");
        jmsearch.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsearchActionPerformed(evt);
            }
        });

        jmfind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmfind.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmfind.setForeground(new java.awt.Color(255, 0, 51));
        jmfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opac/srch.png"))); // NOI18N
        jmfind.setText("Find");
        jmfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmfindActionPerformed(evt);
            }
        });
        jmsearch.add(jmfind);

        jMenuBar1.add(jmsearch);

        jMenu1.setForeground(new java.awt.Color(255, 0, 51));
        jMenu1.setText("Account");
        jMenu1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem1.setText("Sign In");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jmabout.setForeground(new java.awt.Color(255, 0, 51));
        jmabout.setText("About");
        jmabout.setContentAreaFilled(false);
        jmabout.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmabout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jmabout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jmservices.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmservices.setForeground(new java.awt.Color(255, 0, 51));
        jmservices.setText("Services");
        jmservices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmservicesActionPerformed(evt);
            }
        });
        jmabout.add(jmservices);
        jmabout.add(jSeparator1);

        jmmisvis.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmmisvis.setForeground(new java.awt.Color(255, 0, 51));
        jmmisvis.setText("Mission/Vision");
        jmmisvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmmisvisActionPerformed(evt);
            }
        });
        jmabout.add(jmmisvis);
        jmabout.add(jSeparator2);

        jmrules.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmrules.setForeground(new java.awt.Color(255, 0, 51));
        jmrules.setText("Rules and Regulation");
        jmrules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmrulesActionPerformed(evt);
            }
        });
        jmabout.add(jmrules);

        jMenuBar1.add(jmabout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblopac2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopac2MouseEntered
        // TODO add your handling code here:
        this.lblopac2.setForeground(Color.BLACK);
        this.lblopac2.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblopac2MouseEntered

    private void lblopac2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopac2MouseExited
        // TODO add your handling code here:
        this.lblopac2.setForeground(Color.WHITE);
        this.lblopac2.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblopac2MouseExited

    private void lblopac2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopac2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_lblopac2MouseClicked

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
        // TODO add your handling code here:
        
        String full = txtfull.getText();
        String usr = txtuser.getText();
        String pass = txtpass.getText();
        String compas = txtconpass.getText();
        
         try {
             cn.rs = cn.stmt.executeQuery("SELECT * from register WHERE adminFULLNAME = '" + full + "' or adminUSERNAME = '" + usr + "' ");
             cnn.rs = cnn.stmt.executeQuery("SELECT authCODE FROM authentication WHERE authCODE = '" + txtauth.getText() + "'");            
            
             //String cod = cn.rs.getString("authCODE");
             //String aut = txtauth.getText();
          if (cn.rs.next()==true)
        {
            JOptionPane.showMessageDialog(null,"Fullname or Username is Already Taken!!");
        }    
        else if (txtfull.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Fullname is Empty");
        }
        else if (cbxcourse.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(null,"Please Select a Course!!!");
        }
        else if (txtauth.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Authentication Code is Empty");
        }
        else if (cnn.rs.next()== false)
        {
            JOptionPane.showMessageDialog(null,"Authentication Code is Invalid");
        }
        else if (txtuser.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Username is Empty");
        }
        else if (txtpass.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Password is Empty");
        }
        else if (txtconpass.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Confirm Password is Empty");
        }
        else if (!pass.equals(compas))
        {
            JOptionPane.showMessageDialog(null,"Password Didnt Match");
        }else if (chckbxtac.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null,"Please Check if you Agree on the Terms and Condition");
        }
        else
        {    
           
            cn.stmt.executeUpdate("INSERT INTO register VALUES(null,'" + txtfull.getText() + "','" + cbxcourse.getSelectedItem() +"', '" + txtuser.getText() + "', '" + txtpass.getText() + "')");

            JOptionPane.showMessageDialog(null,"Item record saved successfully");
            
            txtfull.setText(null);
            cbxcourse.setSelectedIndex(-1);
            txtauth.setText(null);
            txtuser.setText(null);
            txtpass.setText(null);
            txtconpass.setText(null);
            chckbxtac.setSelected(false);
            
        }
                }                                     
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"error");
            }
        
    }//GEN-LAST:event_btnregActionPerformed

    private void btnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch1ActionPerformed
        // TODO add your handling code here:
        
            txtfull.setText(null);
            cbxcourse.setSelectedIndex(-1);
            txtauth.setText(null);
            txtuser.setText(null);
            txtpass.setText(null);
            txtconpass.setText(null);
            chckbxtac.setSelected(false);
    }//GEN-LAST:event_btnsearch1ActionPerformed

    private void jmfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmfindActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Zearch().setVisible(true);
    }//GEN-LAST:event_jmfindActionPerformed

    private void jmsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jmsearchActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new loginn().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmservicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmservicesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new serve().setVisible(true);

    }//GEN-LAST:event_jmservicesActionPerformed

    private void jmmisvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmmisvisActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new vismis().setVisible(true);

    }//GEN-LAST:event_jmmisvisActionPerformed

    private void jmrulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmrulesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new rul().setVisible(true);

    }//GEN-LAST:event_jmrulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreg;
    private javax.swing.JButton btnsearch1;
    private javax.swing.JComboBox<String> cbxcourse;
    private javax.swing.JCheckBox chckbxtac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu jmabout;
    private javax.swing.JMenuItem jmfind;
    private javax.swing.JMenuItem jmmisvis;
    private javax.swing.JMenuItem jmrules;
    private javax.swing.JMenu jmsearch;
    private javax.swing.JMenuItem jmservices;
    private javax.swing.JLabel lblopac2;
    private javax.swing.JTextArea ta;
    private javax.swing.JPasswordField txtauth;
    private javax.swing.JPasswordField txtconpass;
    private javax.swing.JTextField txtfull;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
