/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opac;

import java.awt.Color;

/**
 *
 * @author dominic
 */
public class rules extends javax.swing.JFrame {

    /**
     * Creates new form rules
     */
    public rules() {
        this.setResizable(false);
        initComponents();
           lbl.setText("Copyright \u00a9 St. Cecilia's College, Inc. All Rights Reserved. ");
            lc.setLineWrap(true);
        lc.setWrapStyleWord(true);
         cl.setLineWrap(true);
        cl.setWrapStyleWord(true);
           nl.setLineWrap(true);
        nl.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cl = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nl = new javax.swing.JTextArea();
        lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        opc.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        opc.setForeground(new java.awt.Color(255, 255, 255));
        opc.setText("Online Public Access Catalog");
        opc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opcMouseExited(evt);
            }
        });
        getContentPane().add(opc);
        opc.setBounds(580, 80, 340, 40);

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        jLabel1.setText("RULES AND REGULATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 140, 340, 40);

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Library Cards");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 200, 160, 30);

        lc.setBackground(new java.awt.Color(255, 255, 204));
        lc.setColumns(20);
        lc.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        lc.setForeground(new java.awt.Color(51, 51, 51));
        lc.setRows(5);
        lc.setText(" Library cards are given free to all \nstudents for the first issue.\n\n The Library card should be validated at\n the start of the school year for the high\n school students and elementary pupils.\n\n Library cards are non-transferable. A\n pupil/student   caught using  another\n library card will be penalized.\n\n Tampered library cards will not be honored \nand will be confiscated.\n\n Lost library cards should be reported\n immediately to the librarian. The students\n will have to secure another library card\n with a replacement fee of P10.00.\n");
        jScrollPane1.setViewportView(lc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 230, 450, 200);

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Circulation");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 200, 140, 30);

        cl.setBackground(new java.awt.Color(255, 255, 204));
        cl.setColumns(20);
        cl.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        cl.setForeground(new java.awt.Color(51, 51, 51));
        cl.setRows(5);
        cl.setText(" Students can borrow 3 circulation books at a\n time for a period of 3 days for subject\n reference and fiction books. These can be \nrenewed once if there are no prior requests made\n for them.\n\n Faculty members can borrow not more than 2\n titles of books per subject for a loaning\n period of one month. These are not renewable.\n");
        jScrollPane2.setViewportView(cl);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(510, 230, 470, 200);

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Non-Circulating materials- are materials which cannot be borrowed for home use but may be borrowed for");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 440, 910, 30);

        nl.setBackground(new java.awt.Color(255, 255, 204));
        nl.setColumns(20);
        nl.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        nl.setForeground(new java.awt.Color(51, 51, 51));
        nl.setRows(5);
        nl.setText(" General reference materials like encyclopedias, dictionaries, atlases,\n  gazetteers, yearbook, almanacs, handbook and manuals.\n\n Theses/Dissertations\n\n Book-in-sets\n");
        jScrollPane3.setViewportView(nl);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(100, 500, 790, 170);

        lbl.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lbl.setText("Copyright \\u00a9 St. Cecilia's College, Inc. All Rights Reserved.");
        getContentPane().add(lbl);
        lbl.setBounds(320, 670, 380, 17);

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("classroom purposes only. These materials are returned immediately after class use.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 470, 760, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opac/mnsr.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1000, 720);

        setBounds(0, 0, 1016, 724);
    }// </editor-fold>//GEN-END:initComponents

    private void opcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcMouseEntered
        // TODO add your handling code here:
          this.opc.setForeground(Color.BLACK);
        this.opc.setForeground(Color.BLACK);
    }//GEN-LAST:event_opcMouseEntered

    private void opcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcMouseExited
        // TODO add your handling code here:
          this.opc.setForeground(Color.WHITE);
        this.opc.setForeground(Color.WHITE);
    }//GEN-LAST:event_opcMouseExited

    private void opcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_opcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl;
    private javax.swing.JTextArea lc;
    private javax.swing.JTextArea nl;
    private javax.swing.JLabel opc;
    // End of variables declaration//GEN-END:variables
}
