/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opac;

import java.awt.Color;
import javax.swing.Box;

/**
 *
 * @author dominic
 */
public class services extends javax.swing.JFrame {

    /**
     * Creates new form services
     */
    public services() {
        this.setResizable(false);
        initComponents();
         copy.setText("Copyright \u00a9 St. Cecilia's College, Inc. All Rights Reserved. ");
        taa.setLineWrap(true);
        taa.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taa = new javax.swing.JTextArea();
        opa = new javax.swing.JLabel();
        copy = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel1.setText("Here are the various services offered:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 180, 400, 26);

        taa.setEditable(false);
        taa.setBackground(new java.awt.Color(255, 255, 204));
        taa.setColumns(20);
        taa.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        taa.setRows(5);
        taa.setText("1.Reference Service\nIt is concerned with assisting readers in securing information\nand with the proper use of the library resources for study \nand research purposes.\n\n2.Library Orientation\nIt is organized for new students and faculty at the beginning of the \nschool year to give a brief outline of the facilities, services, \npolicies and resources of the library.\n\n3.Circulation Service\nA service responsible for the borrowing and returning of books and\nother materials in the library.\n\n4.Internet use\nA service responsible for the access and usage of the information\navailable online.\n\n5.Technical services \nResponsible for the selection and acquisition of library materials,\ncataloging and classification of library materials. Mechanical\npreparation of books such as stamping of ownership stamp, determining\nif books do not have torn or misplaced pages, pasting of book \nproperties,etc.\n\n\n\n\n\n\n\n\n");
        jScrollPane1.setViewportView(taa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 680, 350);

        opa.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        opa.setForeground(new java.awt.Color(255, 255, 255));
        opa.setText("Online Public Access Catalog");
        opa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opaMouseExited(evt);
            }
        });
        getContentPane().add(opa);
        opa.setBounds(360, 20, 330, 30);

        copy.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        copy.setText("Copyright \\u00a9 St. Cecilia's College, Inc. All Rights Reserved.");
        getContentPane().add(copy);
        copy.setBounds(184, 570, 330, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opac/mn4.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 610);

        setBounds(0, 0, 716, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void opaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opaMouseEntered
        // TODO add your handling code here:
        this.opa.setForeground(Color.BLACK);
        this.opa.setForeground(Color.BLACK);
    }//GEN-LAST:event_opaMouseEntered

    private void opaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opaMouseExited
        // TODO add your handling code here:
        this.opa.setForeground(Color.WHITE);
        this.opa.setForeground(Color.WHITE);
    }//GEN-LAST:event_opaMouseExited

    private void opaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opaMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_opaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new services().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel opa;
    private javax.swing.JTextArea taa;
    // End of variables declaration//GEN-END:variables
}
