/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package opac;
import java.awt.Color;
import javax.swing.Box;

/**
 *
 * @author dominic
 */
public class vision extends javax.swing.JFrame {

    /** Creates new form vision */
    public vision() {
       this.setResizable(false);
       
        
        initComponents();
         lblcopy.setText("Copyright \u00a9 St. Cecilia's College, Inc. All Rights Reserved. ");
       taa.setLineWrap(true);
        taa.setWrapStyleWord(true);
         too.setLineWrap(true);
        too.setWrapStyleWord(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        opac1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        too = new javax.swing.JTextArea();
        lblcopy = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        setSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Vision:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 210, 90, 30);

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        jLabel2.setText("Library System");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 160, 210, 50);

        opac1.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        opac1.setForeground(new java.awt.Color(255, 255, 255));
        opac1.setText("Online Public Access Catalog");
        opac1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opac1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opac1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opac1MouseExited(evt);
            }
        });
        getContentPane().add(opac1);
        opac1.setBounds(280, 10, 340, 40);

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Mission:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 390, 100, 30);

        taa.setEditable(false);
        taa.setBackground(new java.awt.Color(255, 255, 204));
        taa.setColumns(20);
        taa.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        taa.setForeground(new java.awt.Color(51, 51, 51));
        taa.setLineWrap(true);
        taa.setRows(5);
        taa.setText("Saint Cecilia’s College Library System aspires to provide\noutstanding information resources and services that advance\nresearch and learning, support the school’s vision, mission,\ngoals and objectives in producing globally competitive \nleaders and professionals.");
        jScrollPane3.setViewportView(taa);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(40, 240, 570, 140);

        too.setEditable(false);
        too.setBackground(new java.awt.Color(255, 255, 204));
        too.setColumns(20);
        too.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        too.setForeground(new java.awt.Color(51, 51, 51));
        too.setLineWrap(true);
        too.setRows(5);
        too.setText("The Saint Cecilia’s College Library System supports and \nenriches the instructional and research needs of the \nCecilian community through the stewardship of scholarly \ninformation and the delivery of information services.");
        jScrollPane2.setViewportView(too);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 420, 570, 130);

        lblcopy.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblcopy.setText("Copyright \\u00a9 St. Cecilia's College, Inc. All Rights Reserved.");
        getContentPane().add(lblcopy);
        lblcopy.setBounds(150, 560, 340, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opac/mn4.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 630, 600);

        setBounds(0, 0, 645, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void opac1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opac1MouseEntered
        // TODO add your handling code here:
          this.opac1.setForeground(Color.BLACK);
        this.opac1.setForeground(Color.BLACK);
    }//GEN-LAST:event_opac1MouseEntered

    private void opac1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opac1MouseExited
        // TODO add your handling code here:
          this.opac1.setForeground(Color.WHITE);
        this.opac1.setForeground(Color.WHITE);
    }//GEN-LAST:event_opac1MouseExited

    private void opac1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opac1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_opac1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblcopy;
    private javax.swing.JLabel opac1;
    private javax.swing.JTextArea taa;
    private javax.swing.JTextArea too;
    // End of variables declaration//GEN-END:variables

}
