/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opac;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author dominic
 */
public class Zearch extends javax.swing.JFrame {

  
    connection cn =  new connection();
    
    public Zearch() {
        
                 
        initComponents(); 
        cbitm.setSelectedIndex(-1);
         
        jMenu1.setText("Account");
        jMenuBar1.add(Box.createHorizontalGlue());
        jMenuBar1.add(jMenu1);
        
        tar1.setLineWrap(true);
        tar1.setWrapStyleWord(true);
        tar2.setLineWrap(true);
        tar2.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblopac = new javax.swing.JLabel();
        btnsrch = new javax.swing.JButton();
        src = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbitm = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblacc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbllocs = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblclass = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblauth = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblcop = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblvol = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbltit = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblsertit = new javax.swing.JLabel();
        lblcol = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblpubplc = new javax.swing.JLabel();
        lblpub = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbledit = new javax.swing.JLabel();
        lblathr = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblloc = new javax.swing.JLabel();
        lblisbn = new javax.swing.JLabel();
        lblc1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblsta = new javax.swing.JLabel();
        lblrem = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tar1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tar2 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        lblc2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblc3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmsearch = new javax.swing.JMenu();
        jmfind = new javax.swing.JMenuItem();
        jmabout = new javax.swing.JMenu();
        jmservices = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmmisvis = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmrules = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 0));
        setMinimumSize(new java.awt.Dimension(1000, 721));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setFillsViewportHeight(true);
        jTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleParent(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 950, 160);

        lblopac.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        lblopac.setForeground(new java.awt.Color(255, 255, 255));
        lblopac.setText("Online Public Access Catalog");
        lblopac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblopacMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblopacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblopacMouseExited(evt);
            }
        });
        getContentPane().add(lblopac);
        lblopac.setBounds(160, 80, 370, 40);

        btnsrch.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnsrch.setForeground(new java.awt.Color(204, 0, 0));
        btnsrch.setText("Search");
        btnsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsrch);
        btnsrch.setBounds(720, 150, 120, 30);
        getContentPane().add(src);
        src.setBounds(340, 150, 350, 30);

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Select Keyword:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 160, 30);

        cbitm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Author", "Location Symbol", "Accession Number", "Book Location", " " }));
        getContentPane().add(cbitm);
        cbitm.setBounds(190, 150, 140, 30);

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setText(":");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 170, 10, 19);

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(850, 150, 120, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        lblacc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblacc.setForeground(new java.awt.Color(204, 0, 0));
        lblacc.setText("None");
        lblacc.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblaccInputMethodTextChanged(evt);
            }
        });
        lblacc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblaccPropertyChange(evt);
            }
        });
        jPanel1.add(lblacc);
        lblacc.setBounds(170, 10, 110, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Location Symbol:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 120, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Accession Number :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 10, 120, 14);

        lbllocs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbllocs.setForeground(new java.awt.Color(204, 0, 0));
        lbllocs.setText("None");
        lbllocs.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbllocsInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lbllocs);
        lbllocs.setBounds(170, 40, 110, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Classification Number:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 70, 130, 14);

        lblclass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblclass.setForeground(new java.awt.Color(204, 0, 0));
        lblclass.setText("None");
        lblclass.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblclassInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblclass);
        lblclass.setBounds(170, 70, 110, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Author Number:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 100, 120, 14);

        lblauth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblauth.setForeground(new java.awt.Color(204, 0, 0));
        lblauth.setText("None");
        lblauth.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblauthInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblauth);
        lblauth.setBounds(170, 100, 110, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Copyright Year:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 130, 120, 14);

        lblcop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcop.setForeground(new java.awt.Color(204, 0, 0));
        lblcop.setText("None");
        lblcop.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblcopInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblcop);
        lblcop.setBounds(170, 130, 110, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Volumes:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 160, 120, 14);

        lblvol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblvol.setForeground(new java.awt.Color(204, 0, 0));
        lblvol.setText("None");
        lblvol.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblvolInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblvol);
        lblvol.setBounds(170, 160, 110, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Title");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(290, 10, 60, 14);

        lbltit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltit.setForeground(new java.awt.Color(204, 0, 0));
        lbltit.setText("None");
        lbltit.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbltitInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lbltit);
        lbltit.setBounds(430, 10, 500, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Series Title:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(290, 100, 100, 14);

        lblsertit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblsertit.setForeground(new java.awt.Color(204, 0, 0));
        lblsertit.setText("None");
        lblsertit.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblsertitInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblsertit);
        lblsertit.setBounds(400, 100, 190, 14);

        lblcol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcol.setForeground(new java.awt.Color(204, 0, 0));
        lblcol.setText("None");
        lblcol.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblcolInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblcol);
        lblcol.setBounds(430, 70, 160, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Collation:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(290, 70, 120, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Publication Place:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 40, 120, 14);

        lblpubplc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblpubplc.setForeground(new java.awt.Color(204, 0, 0));
        lblpubplc.setText("None");
        lblpubplc.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblpubplcInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblpubplc);
        lblpubplc.setBounds(430, 40, 140, 14);

        lblpub.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblpub.setForeground(new java.awt.Color(204, 0, 0));
        lblpub.setText("None");
        lblpub.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblpubInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblpub);
        lblpub.setBounds(120, 250, 160, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Publisher:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 250, 130, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Edition:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 220, 120, 14);

        lbledit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbledit.setForeground(new java.awt.Color(204, 0, 0));
        lbledit.setText("None");
        lbledit.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbleditInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lbledit);
        lbledit.setBounds(120, 220, 150, 14);

        lblathr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblathr.setForeground(new java.awt.Color(204, 0, 0));
        lblathr.setText("None");
        lblathr.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblathrInputMethodTextChanged(evt);
            }
        });
        lblathr.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblathrPropertyChange(evt);
            }
        });
        jPanel1.add(lblathr);
        lblathr.setBounds(120, 190, 150, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Author:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 190, 120, 14);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Location:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(290, 130, 100, 14);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("ISBN:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(290, 160, 120, 14);

        lblloc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblloc.setForeground(new java.awt.Color(204, 0, 0));
        lblloc.setText("None");
        lblloc.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbllocInputMethodTextChanged(evt);
            }
        });
        lblloc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbllocPropertyChange(evt);
            }
        });
        jPanel1.add(lblloc);
        lblloc.setBounds(400, 130, 160, 14);

        lblisbn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblisbn.setForeground(new java.awt.Color(204, 0, 0));
        lblisbn.setText("None");
        lblisbn.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblisbnInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblisbn);
        lblisbn.setBounds(430, 160, 220, 14);

        lblc1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblc1.setForeground(new java.awt.Color(204, 0, 0));
        lblc1.setText("None");
        lblc1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblc1InputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblc1);
        lblc1.setBounds(430, 190, 140, 14);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Co-Author:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(290, 190, 130, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Status:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(590, 220, 80, 14);

        lblsta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblsta.setForeground(new java.awt.Color(204, 0, 0));
        lblsta.setText("None");
        lblsta.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblstaInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblsta);
        lblsta.setBounds(710, 220, 110, 14);

        lblrem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblrem.setForeground(new java.awt.Color(204, 0, 0));
        lblrem.setText("None");
        lblrem.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblremInputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblrem);
        lblrem.setBounds(710, 250, 220, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Remarks:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(590, 250, 80, 14);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Tracing:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(580, 40, 70, 14);

        tar1.setColumns(20);
        tar1.setRows(5);
        jScrollPane2.setViewportView(tar1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(670, 40, 260, 70);

        tar2.setColumns(20);
        tar2.setRows(5);
        jScrollPane3.setViewportView(tar2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(670, 130, 260, 70);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Note Area:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(580, 130, 70, 14);

        lblc2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblc2.setForeground(new java.awt.Color(204, 0, 0));
        lblc2.setText("None");
        lblc2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblc2InputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblc2);
        lblc2.setBounds(430, 220, 140, 14);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Co-Author:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(290, 220, 120, 14);

        lblc3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblc3.setForeground(new java.awt.Color(204, 0, 0));
        lblc3.setText("None");
        lblc3.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblc3InputMethodTextChanged(evt);
            }
        });
        jPanel1.add(lblc3);
        lblc3.setBounds(430, 250, 140, 14);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Co-Author:");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(290, 250, 120, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 380, 950, 280);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opac/mnsr.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1000, 721);

        jmsearch.setForeground(new java.awt.Color(255, 0, 51));
        jmsearch.setText("Search");
        jmsearch.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsearchActionPerformed(evt);
            }
        });

        jmfind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmfind.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmfind.setForeground(new java.awt.Color(255, 0, 51));
        jmfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opac/srch.png"))); // NOI18N
        jmfind.setText("Find");
        jmfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmfindActionPerformed(evt);
            }
        });
        jmsearch.add(jmfind);

        jMenuBar1.add(jmsearch);

        jmabout.setForeground(new java.awt.Color(255, 0, 51));
        jmabout.setText("About");
        jmabout.setContentAreaFilled(false);
        jmabout.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmabout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jmabout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jmservices.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmservices.setForeground(new java.awt.Color(255, 0, 51));
        jmservices.setText("Services");
        jmservices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmservicesActionPerformed(evt);
            }
        });
        jmabout.add(jmservices);
        jmabout.add(jSeparator1);

        jmmisvis.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmmisvis.setForeground(new java.awt.Color(255, 0, 51));
        jmmisvis.setText("Mission/Vision");
        jmmisvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmmisvisActionPerformed(evt);
            }
        });
        jmabout.add(jmmisvis);
        jmabout.add(jSeparator2);

        jmrules.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jmrules.setForeground(new java.awt.Color(255, 0, 51));
        jmrules.setText("Rules and Regulation");
        jmrules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmrulesActionPerformed(evt);
            }
        });
        jmabout.add(jmrules);

        jMenuBar1.add(jmabout);

        jMenu1.setForeground(new java.awt.Color(255, 0, 51));
        jMenu1.setText("Account");
        jMenu1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem1.setText("Sign In");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 0, 51));
        jMenuItem2.setText("Register");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void lblopacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopacMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_lblopacMouseClicked

    private void lblopacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopacMouseEntered
        // TODO add your handling code here:
        this.lblopac.setForeground(Color.BLACK);
        this.lblopac.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblopacMouseEntered

    private void lblopacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopacMouseExited
        // TODO add your handling code here:
        this.lblopac.setForeground(Color.WHITE);
        this.lblopac.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblopacMouseExited

    private void btnsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchActionPerformed
        try {
            // TODO add your handling code here:
            
            String tit = "Title";
            String au = "Author";
            String acc = "Accession Number"; 
            String bloc = "Book Location"; 
            String locs = "Location Symbol"; 
            
            
            if (cn.rs.next()==true)
            {
              }
            else if (cbitm.getSelectedIndex() == -1)            {
                JOptionPane.showMessageDialog(null,"Keyword is Empty");
          }
            else
                
            
            
            if (cbitm.getSelectedItem().equals(tit))
            {
                
                try {
                    cn.rs = cn.stmt.executeQuery("SELECT `Title`,`Author`,`AccessionNo`, `LocationSymbol`,`ClassificationNo`,`Location`,`Status` from recordss WHERE Title LIKE '" + src.getText() +  "%'");
                    
                    jTable1.setModel(DbUtils.resultSetToTableModel(cn.rs));
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Zearch.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            
            else if (cbitm.getSelectedItem().equals(au))
            {
                
                
                
                try {
                    cn.rs = cn.stmt.executeQuery("SELECT `Title`,`Author`,`AccessionNo`, `LocationSymbol`,`ClassificationNo`,`Location`,`Status` from recordss WHERE Author LIKE '" + src.getText() + "%'");
                    
                    jTable1.setModel(DbUtils.resultSetToTableModel(cn.rs));
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Zearch.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            else if (cbitm.getSelectedItem().equals(acc))
            {
                
                
                try {
                    cn.rs = cn.stmt.executeQuery("SELECT `Title`,`Author`,`AccessionNo`, `LocationSymbol`,`ClassificationNo`,`Location`,`Status` from recordss  WHERE AccessionNo LIKE '" + src.getText() + "%'");
                    
                    jTable1.setModel(DbUtils.resultSetToTableModel(cn.rs));
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Zearch.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if (cbitm.getSelectedItem().equals(bloc))
            {
                
                
                
                
                try {
                    cn.rs = cn.stmt.executeQuery("SELECT `Title`,`Author`,`AccessionNo`, `LocationSymbol`,`ClassificationNo`,`Location`,`Status` from recordss WHERE Location LIKE '" + src.getText() + "%'");
                    
                    jTable1.setModel(DbUtils.resultSetToTableModel(cn.rs));
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Zearch.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if (cbitm.getSelectedItem().equals(locs))
            {
                
                
                
                
                try {
                    cn.rs = cn.stmt.executeQuery("SELECT `Title`,`Author`,`AccessionNo`, `LocationSymbol`,`ClassificationNo`,`Location`,`Status`s from recordss WHERE LocationSymbol LIKE '" + src.getText() + "%'");
                    
                    jTable1.setModel(DbUtils.resultSetToTableModel(cn.rs));
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Zearch.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
           
            
            else
            {
                JOptionPane.showMessageDialog(null, "Nothing Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Zearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsrchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cbitm.setSelectedIndex(-1);
        src.setText(null);
        jTable1.setModel(new DefaultTableModel());
                
                lblacc.setText("None");
                lbllocs.setText("None");
                lbltit.setText("None");
                lblvol.setText("None");
                lblcop.setText("None");
                lblauth.setText("None");
                lblclass.setText("None");
                lblathr.setText("None");
                lbledit.setText("None");
                lblpub.setText("None");
                lblpubplc.setText("None");
                lblcol.setText("None");
                lblsertit.setText("None");
                lblloc.setText("None");
                lblisbn.setText("None");
                lblc1.setText("None");
                lblc2.setText("None");
                lblc3.setText("None");
                lblsta.setText("None");
                lblrem.setText("None");
                tar1.setText(null);
                tar2.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmfindActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Zearch().setVisible(true);
    }//GEN-LAST:event_jmfindActionPerformed

    private void jmsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jmsearchActionPerformed

    private void jmservicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmservicesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new serve().setVisible(true);

    }//GEN-LAST:event_jmservicesActionPerformed

    private void jmmisvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmmisvisActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new vismis().setVisible(true);

    }//GEN-LAST:event_jmmisvisActionPerformed

    private void jmrulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmrulesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new rul().setVisible(true);

    }//GEN-LAST:event_jmrulesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new loginn().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new reg().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int roww = jTable1.getSelectedRow();
        int col = 2; // ID is the first Column
        Object idd = jTable1.getValueAt( roww, col );

        lblacc.setText(idd.toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void lblaccInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblaccInputMethodTextChanged
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_lblaccInputMethodTextChanged

    private void lbllocsInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbllocsInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbllocsInputMethodTextChanged

    private void lblaccPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblaccPropertyChange
        // TODO add your handling code here:
          try {
            cn.rs = cn.stmt.executeQuery("SELECT * from recordss WHERE AccessionNo = '" + lblacc.getText() + "' ");

            if (cn.rs.next()) {

                
                lbllocs.setText(cn.rs.getString("LocationSymbol"));
                lbltit.setText(cn.rs.getString("Title"));
                lblvol.setText(cn.rs.getString("Volumes"));
                lblcop.setText(cn.rs.getString("CopyrightYear"));
                lblauth.setText(cn.rs.getString("AuthorNo"));
                lblclass.setText(cn.rs.getString("ClassificationNo"));
                lblathr.setText(cn.rs.getString("Author"));
                lbledit.setText(cn.rs.getString("Edition"));
                lblpub.setText(cn.rs.getString("Publisher"));
                lblpubplc.setText(cn.rs.getString("PublicationPlace"));
                lblcol.setText(cn.rs.getString("Collation"));
                lblsertit.setText(cn.rs.getString("SeriesTitle"));
                lblloc.setText(cn.rs.getString("Location"));
                lblisbn.setText(cn.rs.getString("ISBN"));
                lblc1.setText(cn.rs.getString("FCoAuthor"));
                lblc2.setText(cn.rs.getString("SCoAuthor"));
                lblc3.setText(cn.rs.getString("TCoAuthor"));
                lblsta.setText(cn.rs.getString("Status"));
                lblrem.setText(cn.rs.getString("Remarks"));
                tar1.setText(cn.rs.getString("Tracing"));
                tar2.setText(cn.rs.getString("NoteArea"));
                
            } else {
               
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error..!!");
        }
    }//GEN-LAST:event_lblaccPropertyChange

    private void lblclassInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblclassInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblclassInputMethodTextChanged

    private void lblauthInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblauthInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblauthInputMethodTextChanged

    private void lblcopInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblcopInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcopInputMethodTextChanged

    private void lblvolInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblvolInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblvolInputMethodTextChanged

    private void lbltitInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbltitInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltitInputMethodTextChanged

    private void lblsertitInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblsertitInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblsertitInputMethodTextChanged

    private void lblcolInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblcolInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcolInputMethodTextChanged

    private void lblpubplcInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblpubplcInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblpubplcInputMethodTextChanged

    private void lblpubInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblpubInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblpubInputMethodTextChanged

    private void lbleditInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbleditInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbleditInputMethodTextChanged

    private void lblathrInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblathrInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblathrInputMethodTextChanged

    private void lblathrPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblathrPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblathrPropertyChange

    private void lbllocInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbllocInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbllocInputMethodTextChanged

    private void lbllocPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbllocPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lbllocPropertyChange

    private void lblisbnInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblisbnInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblisbnInputMethodTextChanged

    private void lblc1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblc1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblc1InputMethodTextChanged

    private void lblstaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblstaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblstaInputMethodTextChanged

    private void lblremInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblremInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblremInputMethodTextChanged

    private void lblc2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblc2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblc2InputMethodTextChanged

    private void lblc3InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblc3InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblc3InputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnsrch;
    private javax.swing.JComboBox<String> cbitm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu jmabout;
    private javax.swing.JMenuItem jmfind;
    private javax.swing.JMenuItem jmmisvis;
    private javax.swing.JMenuItem jmrules;
    private javax.swing.JMenu jmsearch;
    private javax.swing.JMenuItem jmservices;
    private javax.swing.JLabel lblacc;
    private javax.swing.JLabel lblathr;
    private javax.swing.JLabel lblauth;
    private javax.swing.JLabel lblc1;
    private javax.swing.JLabel lblc2;
    private javax.swing.JLabel lblc3;
    private javax.swing.JLabel lblclass;
    private javax.swing.JLabel lblcol;
    private javax.swing.JLabel lblcop;
    private javax.swing.JLabel lbledit;
    private javax.swing.JLabel lblisbn;
    private javax.swing.JLabel lblloc;
    private javax.swing.JLabel lbllocs;
    private javax.swing.JLabel lblopac;
    private javax.swing.JLabel lblpub;
    private javax.swing.JLabel lblpubplc;
    private javax.swing.JLabel lblrem;
    private javax.swing.JLabel lblsertit;
    private javax.swing.JLabel lblsta;
    private javax.swing.JLabel lbltit;
    private javax.swing.JLabel lblvol;
    private javax.swing.JTextField src;
    private javax.swing.JTextArea tar1;
    private javax.swing.JTextArea tar2;
    // End of variables declaration//GEN-END:variables

}